apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/local/devops-trabalho/sqlserver
