apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
spec:
  storageClassName: manual
  volumeName: sqlserver-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
