package br.edu.infnet.juliopedidoapi.model.domain;

public enum StatusPedido {
	PRONTO_PARA_RETIRADA, ABERTO, EM_ATENDIMENTO, ORCADO, EM_EXECUCAO, AGUARDANDO_MATERIAIS, AGUARDANDO_APROVACAO,
	REPROVADO, APROVADO, CONCLUIDO, CANCELADO, PENDENTE;
}
