package br.edu.infnet.JulioJubiladoapi.model.domain;

public enum StatusTicket {
	PRONTO_PARA_RETIRADA, ABERTO, EM_ATENDIMENTO, ORCADO, EM_EXECUCAO, AGUARDANDO_MATERIAIS, AGUARDANDO_APROVACAO,
	REPROVADO, APROVADO, CONCLUIDO, CANCELADO;
}
