spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:127.0.0.1}:${DB_PORT:1433};databaseName=${DB_NAME:julio_dev};encrypt=${DB_ENCRYPT:true};trustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:true}
    username: ${DB_APP_USERNAME:${DB_USERNAME:sa}}
    password: ${DB_APP_PASSWORD:${DB_PASSWORD:SenhaForte@123}}
  jpa:
    hibernate:
      ddl-auto: validate
